### ISSUE TITLE
Hades/Balatro  style difficulty system

### ISSUE THREAD

**Issue by Masbirb** [landgreen/n-gon#251] opened 2024-05-10 21:32 UTC
I currently dislike the current difficulty system as it feels like hard is slowly becoming more of what normal was a while ago as more game breaks are added.
The two ideas I have is either a Balatro style stake system or a Hades style heat system.
Difficulty ideas in no particular order 
Eternal junk percentage 
Less tech choices
Reduced ammo gain
Reduced starting ammo
More bosses
Mobs now regen health
Hexagon now attacks faster
No ammo in the final level
More gauntlet bosses

**Comment by landgreen** [comment] 2024-05-11 16:26
not a bad idea.  I like being very clear about what changes with each new difficulty level.
See the difficulty change listed might motivate more people to try harder levels
What's a good n-gon (physics, simulation, AI) themed name for difficulty levels? (temperature?)

these ideas have balancing issues
   Reduced ammo gain
   Reduced starting ammo
   No ammo in the final level
   eternal junk percentage
these might be interesting (and many are already in the game)
   more bosses
   more mobs
   mobs attack faster
   mobs regen health
   mobs move faster
   reduced heals
   reduced damage done
   increased damage taken
   -1 choice for tech, field, gun
   no starting power ups (heal, research)

**Comment by 3xionDev** [comment] 2024-05-11 17:08
i think it would be hilarious if the name for difficulty was just β, since β is a physics constant (i think) and it would be really funny if people had no idea what the line `β += 1` in the console meant

**Comment by corneeme** [comment] 2024-05-15 19:01
haha, what if also they have increased detection range or certain mobs get buffs on harder difficulties

**Comment by landgreen** [comment] 2024-05-18 18:14
**constraint** - explicit changes to the game to increase difficulty
  constraint has understandable text explanations
  add a n-gon face char next to each discrete constraint win (use local storage)
  make current constraints easier to see
    in pause menu
    before game begins in the settings menu
      maybe make it's own details menu eventually
      display on load screen?  top left?
  difficulty should still increase with each level
    constraints will be in addition to that ramping
  constraints
    remove chance to find tech from mobs
    more mobs
    more bosses
    mobs attack faster
    mobs move faster
    no starting power ups (heal, research)
    reduced heals
    reduced damage done
    increased damage taken
    mobs regen health
    -1 choice for tech, field, gun

**Comment by kgurchiek** [comment] 2024-05-19 02:28
> What's a good n-gon (physics, simulation, AI) themed name for difficulty levels?
Maybe a name related to entropy could work for a higher difficulty with a lot of mobs, representing a large amount of particles making it more chaotic?

**Comment by landgreen** [comment] 2024-05-19 02:40
I'm going with "constraints" right now.  It has a math/science vibe and it also has the correct connotation.  I was also considering parameters.  Heat would be a good entropy related term, but I think Hades already uses that term.

**Comment by kgurchiek** [comment] 2024-05-19 12:54
I think "parameters" would make more sense to the average user, to me if it isn't made clear that it's in the context of ai "constraints" sounds like it'll be different limitations for challenges (like "no fields allowed") rather than just any change in the game that affects difficulty (like an increase in enemy attack speed)

**Comment by landgreen** [comment] 2024-05-20 02:46
working on a rough design of the constraint layout and levels
<img width="509" alt="Screenshot 2024-05-19 at 7 46 43 PM" src="https://github.com/landgreen/n-gon/assets/21106570/67a61c61-9130-4cfb-a37f-f1be9ea5c906">

**Comment by landgreen** [comment] 2024-05-25 15:50
More progress on interface style.
This UI stuff takes forever, but I think I'm not ready to write the code and then I'll have to work on balance for a bit.
<img width="462" alt="Screenshot 2024-05-25 at 8 49 51 AM" src="https://github.com/landgreen/n-gon/assets/21106570/7ee3226b-f589-41b0-bbd4-9c07b43d71b1">

**Comment by Masbirb** [comment] 2024-05-25 23:01
Nice you went with the balatro style of difficulty modes

**Comment by landgreen** [comment] 2024-05-25 23:09
Yeah, the other option (Hades style) was letting people pick their own difficulty effects.  It seems like it would be a fun choice, but I was worried it would get confusing and it would hide the feeling of progression.

So, I went with difficulty levels, that have clear delineated rules.  Also, I think an indication of which levels you have cleared will encourage players to rank up to harder levels.

**Comment by Masbirb** [comment] 2024-05-25 23:12
Good point though it would allow for harder modes that people don't think is unfair with Hades but balatro provides more of a sense of progression. Hades also allows for more replay ability though. I would prefer Hades but but balatro style makes players want to stick with this game and enjoy it

**Comment by landgreen** [comment] 2024-05-25 23:15
yeah, I think I'd prefer Hades style too.  I just couldn't figure out how to cleanly show what difficulty levels the player had cleared with the hades checkbox style.

**Comment by AnnonymousNerd87** [comment] 2024-05-28 21:04
I haven't been active for a while, but this seems awesome and I can't wait for it to be sorted out! I think adding a small bonus for completing each constraint (like the bonus bounties for beating a new heat level in hades) would also help encourage progression at higher levels. Maybe an entanglement % which is partially tied to lore which increases the chance of entanglement and undefined?

**Comment by AnnonymousNerd87** [comment] 2024-05-28 21:06
it could be useful for adding lore in a way that doesn't confuse new players other than the undefined system, pointing them towards undefined without getting confusing

**Comment by kgurchiek** [comment] 2024-05-28 23:23
I personally think undefined is fine as it is, the mystery of it makes you curious enough to try to see what secrets it'll access when you win with it

**Comment by kgurchiek** [comment] 2024-05-28 23:27
It's the fact that your own curiosity drives you to complete the challenge that makes it work so well, that might be ruined if there's something that explicitly tells you to try to find it.

**Comment by AnnonymousNerd87** [comment] 2024-05-29 18:09
makes sense, but I feel like this new system should tie into the lore somehow

**Comment by Masbirb** [comment] 2024-05-29 18:12
My idea is difficulty is the system testing how likely it will deal with threats in increasingly difficult scenarios

**Comment by landgreen** [comment] 2024-05-29 22:34
yeah, canonically the game "n-gon" is the self training a quantum computer is doing to evaluate potential situations, so that makes sense.

**Comment by landgreen** [comment] 2024-05-29 22:37
So my new idea is to make the difficulty selection menu a power up that is available on the first level.  Making things more "diegetic" (UI apart of the game) is a goal of mine.

**Comment by kgurchiek** [comment] 2024-05-29 22:38
that's a great idea, I love it when a game's ui is more than just a menu in the start/pause screen

**Comment by landgreen** [comment] 2024-05-29 22:42
<img width="1331" alt="Screenshot 2024-05-29 at 3 42 48 PM" src="https://github.com/landgreen/n-gon/assets/21106570/0663cf37-c63b-459f-b668-e44031ded2c8">

**Comment by kgurchiek** [comment] 2024-05-29 22:51
I imagine it would just stay at your previous game's difficulty

**Comment by kgurchiek** [comment] 2024-05-29 22:52
It might also be fun if instead of a cancel button it has a random difficulty option

**Comment by landgreen** [comment] 2024-05-29 23:11
<img width="692" alt="Screenshot 2024-05-29 at 4 11 03 PM" src="https://github.com/landgreen/n-gon/assets/21106570/5c894330-071d-412d-8e62-bed0d023f100">
this is what I put together in 20 minutes, the colors are kinda messed up and the spacing is off, but it's general idea.  You move a slider, then click to confirm your choice.

**Comment by AnnonymousNerd87** [comment] 2024-05-30 00:38
I think that's if you slide it all the way to the top, and btw yeah
diegetic n-gon sounds awesome, that's one of the reasons I loved hades. I
should return to that game and finish the epilogue.

**Comment by landgreen** [comment] 2024-05-30 04:28
<img width="968" alt="Screenshot 2024-05-29 at 9 27 27 PM" src="https://github.com/landgreen/n-gon/assets/21106570/7ca3c1f8-afb9-4ebb-b18d-05549af16ef6">

ok I've added the UI polish.  I'm pretty happy with everything.  But I have to choose between the left or right.

**Comment by kgurchiek** [comment] 2024-05-30 05:34
I think the left looks a lot better

**Comment by AnnonymousNerd87** [comment] 2024-05-30 16:16
yeah I like the borderless flow of the left

**Comment by landgreen** [comment] 2024-05-31 02:22
<img width="450" alt="Screenshot 2024-05-30 at 7 22 21 PM" src="https://github.com/landgreen/n-gon/assets/21106570/b9d177c8-d88c-4385-948a-4f45ff7f1f6b">

ok I added the borders, but only on mouse over.

**Comment by kgurchiek** [comment] 2024-05-31 04:44
oh yeah that looks really nice

**Comment by kgurchiek** [comment] 2024-06-01 22:39
Are the icons on the right for the difficulties you've beaten?

**Comment by landgreen** [comment] 2024-06-01 23:04
yeah

**Comment by kgurchiek** [comment] 2024-06-01 23:06
Oh that's really cool

**Comment by landgreen** [comment] 2024-06-02 16:05
I didn't make those logos that are just what unicode has available
https://en.wikipedia.org/wiki/Miscellaneous_Symbols
○  ●  ⚆ ⚇ ⚈ ⚉ 
I am just now learning the are "Go markers"  for use in text related to the game "go".
I'm considering the 2 eyes version for the last mode.

**Comment by AnnonymousNerd87** [comment] 2024-06-03 14:47
This is prob. going to be the best update n-gon has gotten since the last update

**Comment by landgreen** [comment] 2024-06-03 14:53
It's been up for about 12 hours.  It was a ton of work behind the scenes, but in the end I tried to reproduce the same balance from before with more delineated difficult levels.

I think experienced players might not see many changes, but I hope new players will have more emersion and a more active experience with difficulty levels.

**Comment by AnnonymousNerd87** [comment] 2024-06-03 14:58
yeah I was watching via email, so I didn't see the update. Looks great,
blends well, and will be very helpful for determining what difficulty I
want to main, like hades.

**Comment by AnnonymousNerd87** [comment] 2024-06-03 23:19
no, it just uses the default setting

**Comment by kgurchiek** [comment] 2024-06-03 23:28
@AnnonymousNerd87 I have a bot that automatically emails people new updates (including the downloaded zip), I can add you to the mailing list if you want

**Comment by AnnonymousNerd87** [comment] 2024-06-04 02:24
no I listed myself as a watcher

**Comment by AnnonymousNerd87** [comment] 2024-06-04 18:58
I like the system so far, but adding a small reward for completing each level would make it feel a little more like hades, maybe a bounty system which gives +1 bonus initial powerups for completing each new difficulty

**Comment by landgreen** [comment] 2024-06-04 23:10
It would be fun to make a progression system like hades, but this is a browser game that people might play on different computers.  I don't want to make people login to accounts and github doesn't even allow that.

**Comment by kgurchiek** [comment] 2024-06-04 23:31
Yes, but you'd lose your progress if you use another device

**Comment by AnnonymousNerd87** [comment] 2024-06-04 23:38
yeah I guess, maybe it could just be a short meeting with the undefined
tentacle monster robot quantum supercomputer thing with new dialogue based
on completing each difficulty while collecting undefined

**Comment by AnnonymousNerd87** [comment] 2024-06-06 22:39
Idea for a name: Decoherence, representing the simulation slowly falling apart and becoming more fixed, causing errors as the values between 0 and 1 decohere and break things, causing power ups to disappear, mobs to appear in greater numbers with more shields, etc., and the whole system is failing, so m needs to collect less undefined to cause undefined.

**Comment by AnnonymousNerd87** [comment] 2024-06-06 22:41
oh and β is a letter in German, so it would be confusing to see what english people would see as z += 1

**Closed** 2024-06-07 00:51 UTC
