### ISSUE TITLE
github pages trouble

### ISSUE THREAD

**Issue by AnnonymousNerd87** [landgreen/n-gon#212] opened 2024-04-19 15:26 UTC
I recently forked n-gon and made a few dumb changes (the physics for some stuff is different), while removing some smart ones (ammo management, death), and everything was running smoothly. I had made a github pages page (?) and it had worked before, but after committing the changes and waiting for the upload the github pages link went down for a while, then when it came back up only the index.html loaded, so when I tried to start the game nothing happened. I didn't even touch the index.html until then so I don't know what went wrong. Here is the link to the repo: https://github.com/AnnonymousNerd87/AnnonymousNerd87.github.io
I have already invited you as a collaborator so we can try to fix it. 

not expecting a response soon, I know school days aren't the best time.

**Comment by landgreen** [comment] 2024-04-20 14:24
The first thing I notice is that you don't have a player.js file

**Comment by kgurchiek** [comment] 2024-04-20 17:41
I think the issue is the extra closing bracket on line 424 of player.js

**Comment by AnnonymousNerd87** [comment] 2024-04-20 17:50
I have a player.js file, I just updated it a bit.

**Comment by AnnonymousNerd87** [comment] 2024-04-20 17:51
I can restore it now, see if it helps

**Comment by kgurchiek** [comment] 2024-04-20 17:52
There's a syntax error in your modified player.js preventing it from running

**Comment by landgreen** [comment] 2024-04-20 17:52
Where is your player.js file?  (I'm in github pages)
<img width="1038" alt="Screenshot 2024-04-20 at 10 52 04 AM" src="https://github.com/landgreen/n-gon/assets/21106570/761b74d8-0673-4ccb-a96d-b0f90bcfaa47">

**Comment by kgurchiek** [comment] 2024-04-20 17:54
@landgreen it isn't loading due to a syntax error, but it does exist https://github.com/AnnonymousNerd87/AnnonymousNerd87.github.io/blob/master/js/player.js

**Comment by AnnonymousNerd87** [comment] 2024-04-20 17:55
I just restored the wipe canvas function I accidentally deleted, testing now

**Comment by AnnonymousNerd87** [comment] 2024-04-20 17:55
nope, still not working

**Comment by AnnonymousNerd87** [comment] 2024-04-20 17:56
let me revert the whole player.js file to an original version

**Comment by AnnonymousNerd87** [comment] 2024-04-20 17:56
I didn't make too much edits in my version, so it should help

**Comment by landgreen** [comment] 2024-04-20 17:57
> @landgreen it isn't loading due to a syntax error, but it does exist https://github.com/AnnonymousNerd87/AnnonymousNerd87.github.io/blob/master/js/player.js

Oh so if you have a syntax error it's hidden in dev tools?  I didn't know that.

**Comment by kgurchiek** [comment] 2024-04-20 17:59
Yeah, if scripts fail to run it won't show them in the sources tab

**Comment by AnnonymousNerd87** [comment] 2024-04-20 18:01
I just fixed the syntax error, saving now

**Comment by AnnonymousNerd87** [comment] 2024-04-20 18:02
it works!

**Comment by AnnonymousNerd87** [comment] 2024-04-20 18:03
thanks landgreen and kgurchiek, I hadn't noticed the syntax error

**Closed** 2024-04-20 18:03 UTC

**Comment by AnnonymousNerd87** [comment] 2024-04-20 18:05
[Screen recording 2024-04-20 11.04.46 AM.webm](https://github.com/landgreen/n-gon/assets/164103476/e71e094b-d3b2-434e-ad16-3c4b50e2537e)

**Comment by AnnonymousNerd87** [comment] 2024-04-20 18:06
man I love indie devs
